### ISSUE TITLE
Won't work with mixed-cased column names

### ISSUE THREAD

**Issue by rcongiu** [outworkers/phantom#622]
Cassandra allows the use of mixed-case for columns and tables.
If the column names are mixed case, there's no way for the generate CQL to access them since it's not quoted.

Even with  ` override val name = "mixedCaseColumn"`, it won't work.
I see in the code there's incomplete provisions for case sensitivity with QueryBuilderConfig, but I also see they're not documented (or I couldn't find it), also, config is in a private immutable member and I do not see how it could be changed. But even it it could, I see in the code the case sensitivity is applied to the table name _only_, not the columns. 

This issue makes this library completely unusable for any Cassandra table with mixed case columns.

**Comment by alexflav23** [comment]
Hi @rcongiu,

We are aware of this and actively working to fix it, you can expect a fix to be deployed within the next 3 days. We will provide a configuration mechanism that will allow easily configuring what kind of patterns the table naming will follow, with a few options available.

- snake_case
- camelCase
- `quotedCase`
- `quotedSnakeCase`

We may even consider offering the ability to generate custom names, so all you will need to do is provide an implicit and the rest will just work.

Regards.

**Comment by rcongiu** [comment]
Cool, thank you.

**Comment by alexflav23** [comment]
Hi @rcongiu This is now fixed in 2.2.0, on Maven Central later today. 

```scala
class MyDb(override val connector: CassandraConnection) extends Database[MyDb)(connector) {

  override implicit val naming: NamingStrategy = NamingStrategy.CamelCase.caseSensitive
}
```

**Comment by drewrobb** [comment]
Hi @alexflav23, where exactly is this implemented? I was attempting to use it, but I don't see any references to `NamingStrategy` in this repo under the tag `org=com.outworkers,name=phantom,version=2.2.0`.

**Comment by alexflav23** [comment]
Hi @drewrobb @rcongiu Apologies, this didn't make the cut in 2.2.0, because of a superb compiler quirk that we are trying hard to get to the bottom of. It's planned to 2.2.4 and it's the branch that will go out next, for now it's still on a PR.

**Comment by drewrobb** [comment]
Hi @alexflav23, I don't think this issue should actually be closed-- the feature you mentioned `NamingStrategy` is for table naming, whereas the issue here is about column naming. As far as I can tell there still isn't a great way to handle cased column names?

**Comment by alexflav23** [comment]
Hi @drewrobb That's a great point, an oversight on my part. That will land shortly.

**Comment by anadoba** [comment]
👍  for this feature request.
I'm in the middle of writing some fancy test matchers in phantom-based project and it turned out we have no control over column names casing... Aaand we're using phantom-generated schema of course.

**Comment by alexflav23** [comment]
@anadoba Alright, we'll escalate support for this feature, that's not a problem.

**Comment by alexflav23** [comment]
@rcongiu @anadoba @drewrobb Overriding column names is now supported properly with no further interference, meaning you can simply override the column name to whatever you want.

```scala
import com.outworkers.phantom.dsl._

abstract class MyTable extends Table[MyTable, Record] {
  object id extends Col[UUID] with PartitionKey {
    override def name = """"This_is_a_anExample"""
  }
}
```
